---
# tasks file for deploy_apache_web
  tasks:
  - name: Check Print Linux Version
    debug: var=ansible_os_family

  - block: # REDHAT BCLOK

      - name: Install Apache Web Server for RedHat
        yum: name=httpd state=latest

      - name: Start WebServer and make it enable on boot for RedHat
        service: name=httpd state=started enabled=yes

      - name: Add HTTP-service to firewall RedHat
        firewalld: service=http permanent=yes state=enabled
        notify: Reload Firewall RedHat

    when: ansible_os_family == "RedHat"

  - block: # DEBIAN BCLOK

      - name: Install Apache Web Server for Debian
        apt: name=apache2 state=latest

      - name: Start WebServer and make it enable on boot for Debian
        service: name=apache2 state=started enabled=yes

      - name: Add HTTP-service to firewall Debian
        ufw: rule=allow name=Apache state=enabled
        notify: Reload Firewall Debian

    when: ansible_os_family == "Debian"

  - name: Generate index.html
    template: src=index.j2 dest={{ destin_file }}/index.html mode=0555
    notify: Restart Apache