
---
- name: Loops
  hosts: node01
  become: true

  tasks:
  - name: MSG
    debug: msg="Hello {{ item }}"
    loop:
      - "1"
      - "2"
      - "3"
      - "4"

  - name: Loop Until
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZZ") == false

  - name: PrintOut
    debug:
      var: output.stduot


...
