
---
- name: Install Apache and upload Web Page
  hosts: all
  become: yes

  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html/

  tasks:
  - name: Install Apache Web Server
    yum: name=httpd state=latest

  - name: Copy MyHomePage to Servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start WebServer and make it enable on boot
    service: name=httpd state=started enabled=yes

  - name: Add HTTP-service to firewall
    firewalld: service=http permanent=yes state=enabled
    notify: Reload Firewall

  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted

  - name: Reload Firewall
    service: name=firewalld state=reloaded

...
