
---
- name: Install Apache and upload Web Page
  hosts: all
  become: yes

  vars:
    source_file: ../MyWebSite/index.j2
    destin_file: /var/www/html/

  tasks:
  - name: Check Print Linux Version
    debug: var=ansible_os_family

  - block: # REDHAT BCLOK

      - name: Install Apache Web Server for RedHat
        yum: name=httpd state=latest

      - name: Start WebServer and make it enable on boot for RedHat
        service: name=httpd state=started enabled=yes

      - name: Add HTTP-service to firewall RedHat
        firewalld: service=http permanent=yes state=enabled
        notify: Reload Firewall RedHat

    when: ansible_os_family == "RedHat"

  - block: # DEBIAN BCLOK

      - name: Install Apache Web Server for Debian
        apt: name=apache2 state=latest

      - name: Start WebServer and make it enable on boot for Debian
        service: name=apache2 state=started enabled=yes

      - name: Add HTTP-service to firewall Debian
        ufw: rule=allow name=Apache state=enabled
        notify: Reload Firewall Debian

    when: ansible_os_family == "Debian"

#  - name: Copy Page
#    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
#    notify: Restart Apache
  - name: Generate index.html
    template: src={{ source_file }} dest={{ destin_file }}/index.html mode=0555
    notify: Restart Apache


  handlers:
  - name: Restart Apache
    service: name=httpd state=restarted
    when: ansible_os_family == "RedHat"

  - name: Restart Apache
    service: name=apache2 state=restarted
    when: ansible_os_family == "Debian"

  - name: Reload Firewall RedHat
    service: name=firewalld state=reloaded

  - name: Reload Firewall Debian
    service: name=ufw state=reloaded


...
